// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const EditorUtils: typeof import('/home/alex/src/fixmoodle/utils/editor-utils')['EditorUtils']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const SettingsStorage: typeof import('/home/alex/src/fixmoodle/utils/storage')['SettingsStorage']
  const browser: typeof import('wxt/browser/chrome')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { EditorUtils } from '/home/alex/src/fixmoodle/utils/editor-utils'
  import('/home/alex/src/fixmoodle/utils/editor-utils')
  // @ts-ignore
  export type { SettingsStorage } from '/home/alex/src/fixmoodle/utils/storage'
  import('/home/alex/src/fixmoodle/utils/storage')
}
